FROM cyberdojofoundation/alpine_glibc:7becbb4
LABEL maintainer=bradcray@gmail.com

ENV CHPL_VERSION 1.25.0
ENV CHPL_HOME /opt/chapel/chapel-${CHPL_VERSION}
ENV PATH ${PATH}:${CHPL_HOME}/bin/linux64-x86_64:${CHPL_HOME}/util

COPY install.sh .
RUN ./install.sh && rm -f ./install.sh
